### ISSUE TITLE
IdleRPG leaderboard reverses sort within levels

### ISSUE THREAD

**Issue by wizjany** [EngineHub/EngineHub-Bot#1]
https://github.com/EngineHub/EngineHub-Bot/blob/f201788aa4d7a5514a0dcf9d217333a50a44e8aa/src/main/java/org/enginehub/discord/module/IdleRPG.java#L96

oldest (ie smaller) level time should be highest on leaderboard, not lowest.

**Comment by me4502** [comment]
Fixed.
